namespace DatabaseCompare.DotLFields
{
    public class AnalogFields
    {
        public static string[] Fields =
        {
            "name ",
            "rtu ",
            "group ",
            "station ",
            "flag.alminh ",
            "flag.clrinh ",
            "flag.evtinh ",
            "flag.cevinh ",
            "flag.bmsg ",
            "flag.priorityDisplay ",
            "flag.safety ",
            "pointtype ",
            "input ",
            "output ",
            "otype ",
            "iengr.rawmin ",
            "iengr.rawmax ",
            "iengr.egumin ",
            "iengr.egumax ",
            "iengr.scaleraw ",
            "units ",
            "hilow.lolim ",
            "hilow.hilim ",
            "hilow.lololim ",
            "hilow.hihilim ",
            "hilow.doithi ",
            "hilow.doithihi ",
            "hilow.doitlo ",
            "hilow.doitlolo ",
            "anain.iospec.external ",
            //"anain.iospec.xmod_format ",
            "anain.type ",
            "oengr.rawmin ",
            "oengr.rawmax ",
            "oengr.egumin ",
            "oengr.egumax ",
            "oengr.scaleraw ",
            "anaout.iospec.external ",
            //"anaout.iospec.xmod_format ",
            "devtmr ",
            "lgcmsc ",
            "sptlolim ",
            "spthilim ",
            "description ",
            "pointClass ",
            "pointSubClass ",
            "shortDesc ",
            "wellunit ",
            "displayOrder "
        };
    }
}
